### ISSUE TITLE
feat: adding/getting incident categories

### ISSUE THREAD

**Issue by andela-anandaa** [AndelaOSP/wire-api#27]
**A: Endpoints for admins to add new incident category:**

```
POST: /categories
```
Payload:
```
{ name, level_id, visible }
```

**B: Endpoint for listing incident categories:**

```
GET: /categories
```

Sample response:
```
[
{
  "id": 1,
  "name": "Theft",
  "level_name": "Red",
  "level_id": 1,
  "visible": 1
},
{
  "id": 1,
  "name": "Noise Disruption",
  "level_name": "Yellow",
  "level_id": 2,
  "visible": 1
}
]
```

**C: Endpoint for listing the level IDs** (to be used on the admin side when adding categories)

```
GET: /levels
```

Sample Response:
```
[
  {
    "id": 1,
    "name": "Red",
   },
  {
    "id": 2,
    "name": "Yellow",
  },
  ...
]
```

**Comment by Mnickii** [comment]
@andela-anandaa does the Admin have a specific identifier? Like a role Id?I notice in the example, the ids are the same. Are those the incident IDs or that's the role Id?
